services:
  - type: web
    name: weatherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python weatherbot.py
    envVars:
      - key: CITY
        value: "South Bend, Indiana"
      - key: LAT
        value: "41.6764"
      - key: LON
        value: "-86.2520"
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false